import { Nav } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Provider from "@/components/Provider";
import ProtectRoute from "@/utils/Protect";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className={"bg-[#0C0C0D] min-h-screen "}>
        <Provider>
          <Nav />

          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
