import { HeaderConfig as HeaderConfigType, exercise } from "@/types";

export const HeaderConfig: RequestInit = {
  headers: {
    "X-RapidAPI-Key": process.env.XRapidAPIKey || "",
    "X-RapidAPI-Host": process.env.XRapidAPIHost || "",
  },
};
export const someOfData: exercise[] = [
  {
    bodyPart: "back 1",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "1",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back 2",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "2",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back 3",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "3",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back 4",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "4",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back5 ",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "5",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back 6",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "6",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back 7",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "7",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "8",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "9",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "10",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "bacewrk",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "bacak",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "bacwek",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back fend ",
    name: "swap",
  },
  {
    bodyPart: "bacfk",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "bacdk",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "bacfk",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "bacak",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back4",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "backf",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "backaa",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back32",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back12",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
  {
    bodyPart: "back12",
    gifUrl: "/images/s6fIeHq0b5EuGl.gif",
    equipment: "waire",
    id: "11",
    target: "back end ",
    name: "swap",
  },
];
